[package]
name = "kvproto"
version = "0.0.1"
keywords = ["TiKV"]

[lib]
name = "kvproto"

[dependencies]
protobuf = "~2.0"
futures = "0.1"
raft = "0.4"

[dependencies.grpcio]
git = "https://github.com/hicqu/grpc-rs"
branch = "v0.4-grpc-1.17"
